# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-f8454601-1bc0-4ea2-baaf-220b6b3265b8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f8454601-1bc0-4ea2-baaf-220b6b3265b8".device = "/dev/disk/by-uuid/f8454601-1bc0-4ea2-baaf-220b6b3265b8";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EB99-05D8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c42416f3-d1ce-4a19-853e-9751e5792d69"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
